### ISSUE TITLE
Unable to deploy Multiple functions when handler function is inside other folder in minikube

### ISSUE THREAD

**Issue by maneet8** [serverless/serverless-kubeless#165]
I am unable to deploy multiple functions when handler function is inside other folder.
Clone the below project, which I have picked up from these examples only and slightly modified the folder structure.

https://github.com/maneet8/testserverlesskubeless.git

Run npm install

Run serverless deploy

I am getting below error on deployment

$ serverless deploy -v
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Unable to find any running pod for read-all. Retrying...
Serverless: Unable to find any running pod for create. Retrying...
Serverless: Unable to find any running pod for read-one. Retrying...
Serverless: Unable to find any running pod for update. Retrying...
Serverless: Unable to find any running pod for delete. Retrying...
Serverless: Unable to find any running pod for delete. Retrying...
Serverless: Unable to find any running pod for create. Retrying...
Serverless: Unable to find any running pod for read-one. Retrying...
Serverless: Unable to find any running pod for update. Retrying...
Serverless: Unable to find any running pod for read-all. Retrying...
Serverless: Unable to find any running pod for delete. Retrying...
Serverless: Unable to find any running pod for read-all. Retrying...
Serverless: Unable to find any running pod for update. Retrying...
Serverless: Unable to find any running pod for read-one. Retrying...
Serverless: Unable to find any running pod for create. Retrying...
Serverless: Unable to find any running pod for read-all. Retrying...
Serverless: Unable to find any running pod for update. Retrying...
Serverless: Unable to find any running pod for read-one. Retrying...
Serverless: Unable to find any running pod for create. Retrying...
Serverless: Unable to find any running pod for delete. Retrying...
Serverless: Giving up, unable to retrieve the status of the read-one deployment.
Serverless: Giving up, unable to retrieve the status of the read-all deployment.

C:\Users\maneet\AppData\Roaming\npm\node_modules\serverless\lib\classes\Error.js:92
    throw new Error(e);
          ^
Error: Unable to retrieve the status of the read-one deployment
    at module.exports.logError (C:\Users\maneet\AppData\Roaming\npm\node_modules\serverless\lib\classes\Error.js:92:11)
    at process.on (C:\Users\maneet\AppData\Roaming\npm\node_modules\serverless\bin\serverless:22:3)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at process.emit (C:\Users\maneet\AppData\Roaming\npm\node_modules\serverless\node_modules\source-map-support\source-map-support.js:461:21)
    at methodName (D:\workdir\testserverlesskubeless\node_modules\bluebird\js\release\debuggability.js:199:33)
    at activeFireEvent (D:\workdir\testserverlesskubeless\node_modules\bluebird\js\release\debuggability.js:242:44)
    at fireRejectionEvent (D:\workdir\testserverlesskubeless\node_modules\bluebird\js\release\debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (D:\workdir\testserverlesskubeless\node_modules\bluebird\js\release\debuggability.js:65:9)
    at Timeout._onTimeout (D:\workdir\testserverlesskubeless\node_modules\bluebird\js\release\debuggability.js:44:14)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

With the same folder structure I am able to deploy on AWS Lambda.

**Comment by andresmgot** [comment]
Yes, that's something that need to be implemented in Kubeless, see this issue for more details:

https://github.com/kubeless/kubeless/issues/803
