### ISSUE TITLE
Can't get example working on minikube.

### ISSUE THREAD

**Issue by Industrial** [serverless/serverless-kubeless#177]
```
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ...
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
📯  Updating kube-proxy configuration ...
🤔  Verifying component health ......
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
```

Whereafter:

```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command info
Serverless: Load command logs
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
/home/tom/Code/Code9/JavaScript/Projects/test-next.js/services/api-serverless/node_modules/serverless-kubeless/lib/config.js:56
      return JSON.parse(this.configMag.data[key]);
                                           ^

TypeError: Cannot read property 'runtime-images' of undefined
    at Config.get (/home/tom/Code/Code9/JavaScript/Projects/test-next.js/services/api-serverless/node_modules/serverless-kubeless/lib/config.js:56:44)
    at Object.getRuntimeDepfile (/home/tom/Code/Code9/JavaScript/Projects/test-next.js/services/api-serverless/node_modules/serverless-kubeless/lib/helpers.js:182:34)
    at ReadStream.s.on (/home/tom/Code/Code9/JavaScript/Projects/test-next.js/services/api-serverless/node_modules/serverless-kubeless/deploy/kubelessDeploy.js:103:39)
    at ReadStream.emit (events.js:193:15)
    at ReadStream.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

Looking at some other tickets, it might have been an env var $KUBECONFIG, but I have no env var defined like this.

I don't know what to do, but the hello world doesn't work on minikube.

Minikube is mentioned here: https://serverless.com/framework/docs/providers/kubeless/guide/installation

**Comment by andresmgot** [comment]
hi @Industrial,

it seems that it's failing to retrieve the Kubeless configuration. That shouldn't be a problem with Minikube. Did you install kubeless in the default namespace? Are you able to retrieve the `kubeless` configuration with `kubectl get configmap -n kubeless`?

**Comment by Industrial** [comment]
```
$ minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100
```

(command I found to get some status printed ..)
```
$ kubectl top node
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

**Comment by Industrial** [comment]
@andresmgot 

I can get to the Kubernetes dashboard with `minikube dashboard`

**Comment by Industrial** [comment]
Ah, my bad. I didn't acttivate/install Kubeless on Minikube correctly.

To prevent this situation, I've created a little shell script. I understand this isn't the most time-efficient method but at least it's fault tolerant ;-)

```
#!/usr/bin/env bash

# Refresh Minikube
minikube stop
minikube delete
minikube start

# Refresh Kubeless
export RELEASE=$(curl -s https://api.github.com/repos/kubeless/kubeless/releases/latest | grep tag_name | cut -d '"' -f 4)
kubectl create ns kubeless
kubectl create -f https://github.com/kubeless/kubeless/releases/download/$RELEASE/kubeless-$RELEASE.yaml

# Refresh Serverless
serverless deploy -v
```

**Comment by andresmgot** [comment]
I am glad you got it finally working. Thanks for the script suggestion!

**Comment by Industrial** [comment]
Ah, that's just for myself until I get accustomed to the layers involved :-)

I'll now try yo migrate some services (Prisma GraphQL, GraphQL-Yoga, some REST stuff) from Docker into serverless/Kubernetes.
