### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable for python3.6 runtime

### ISSUE THREAD

**Issue by engmsaleh** [serverless/serverless-kubeless#179]
When I try to follow the hello world example, I get the following error when I try to invoke the function 
```
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/bitnami/python/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/kubeless.py", line 86, in handler
    raise res
TypeError: Object of type 'bytes' is not JSON serializable
```

**Comment by engmsaleh** [comment]
After I have moved to a new clean cluster, it worked correctly I don't know why

**Comment by andresmgot** [comment]
The example is compatible with python 2.7 I am not sure if the same example is compatible with python 3.6
