### ISSUE TITLE
Feature Request: Configurable retry limit/delay time when checking deployment status.

### ISSUE THREAD

**Issue by d0x2f** [serverless/serverless-kubeless#199]
We have a deployment pipeline that runs `serverless deploy` for about 100 functions as well as autoscaling rules bringing it up to 200 pods.

I think this load during deployment causes the plugin to fail to find new pods within the 3 retry limit here: https://github.com/serverless/serverless-kubeless/blob/b0376313e7607d90a99036bc8c34a024c547e12f/lib/deploy.js#L215

Retrying the deployment pipeline gets further and it takes around 5 retries to get through everything.

It would be great for us to be able to configure the retry limit and/or the delay time between retries to something more reasonable for our use case.

Here's some output from one of our function packages:
```
Deploying /srv/.serverless/alchemy-auth-functions.zip to alchemy-demo
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Deploying function alchemy-auth-add-cluster-admin...
Serverless: Deploying function alchemy-auth-get-batch...
Serverless: Unable to find any running pod for alchemy-auth-add-cluster-admin. Retrying...
Serverless: Unable to find any running pod for alchemy-auth-get-batch. Retrying...
Serverless: Unable to find any running pod for alchemy-auth-add-cluster-admin. Retrying...
Serverless: Function alchemy-auth-list-public-entities successfully deployed
Serverless: Function alchemy-auth-get-entity successfully deployed
Serverless: Function alchemy-auth-list-child-entities successfully deployed
Serverless: Function alchemy-auth-calculate-usage successfully deployed
Serverless: Function alchemy-auth-create-alchemy-user successfully deployed
Serverless: Unable to find any running pod for alchemy-auth-get-batch. Retrying...
Serverless: Function alchemy-auth-list-candidate-entities successfully deployed
Serverless: Function alchemy-auth-create-entity successfully deployed
Serverless: Function alchemy-auth-calculate-created successfully deployed
Serverless: Function alchemy-auth-ping successfully deployed
Serverless: Function alchemy-auth-create-session successfully deployed
Serverless: Function alchemy-auth-get-entity-by-name successfully deployed
Serverless: Function alchemy-auth-unimpersonate-user successfully deployed
Serverless: Function alchemy-auth-create-company successfully deployed
Serverless: Function alchemy-auth-delete-session successfully deployed
Serverless: Function alchemy-auth-create-service-provider successfully deployed
Serverless: Function alchemy-auth-enable-entity successfully deployed
Serverless: Function alchemy-auth-impersonate-user successfully deployed
Serverless: Function alchemy-auth-get-session successfully deployed
Serverless: Function alchemy-auth-execute successfully deployed
Serverless: Function alchemy-auth-update-entity successfully deployed
Serverless: Function alchemy-auth-disable-entity successfully deployed
Serverless: Function alchemy-auth-patch-entity successfully deployed
Serverless: Function alchemy-auth-set-roles-on-session successfully deployed
Serverless: Unable to find any running pod for alchemy-auth-add-cluster-admin. Retrying...
Serverless: Unable to find any running pod for alchemy-auth-get-batch. Retrying...
Serverless: Unable to find any running pod for alchemy-auth-add-cluster-admin. Retrying...
Serverless: Unable to find any running pod for alchemy-auth-get-batch. Retrying...
Serverless: Giving up, unable to retrieve the status of the alchemy-auth-add-cluster-admin deployment. 
Serverless: Unable to find any running pod for alchemy-auth-add-cluster-admin. Retrying...
Serverless: Giving up, unable to retrieve the status of the alchemy-auth-get-batch deployment. 
 
  Error --------------------------------------------------
 
  Error: Found errors while processing the given functions:
  Unable to retrieve the status of the alchemy-auth-add-cluster-admin deployment
  Unable to retrieve the status of the alchemy-auth-get-batch deployment
      at Object.checkFinished (/srv/node_modules/serverless-kubeless/lib/helpers.js:211:14)
      at /srv/node_modules/serverless-kubeless/lib/deploy.js:564:21
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:75:30
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:75:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:64:4)
      at Module._compile (internal/modules/cjs/loader.js:955:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
      at Module.load (internal/modules/cjs/loader.js:811:32)
      at Function.Module._load (internal/modules/cjs/loader.js:723:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
      at internal/main/run_main_module.js:17:11
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.14.1
     Framework Version:         1.60.5
     Plugin Version:            3.2.7
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 
Serverless: Unable to find any running pod for alchemy-auth-get-batch. Retrying...
```

**Comment by andresmgot** [comment]
Sure, the retry interval can be found in the same place:

https://github.com/serverless/serverless-kubeless/blob/b0376313e7607d90a99036bc8c34a024c547e12f/lib/deploy.js#L282

Can you confirm if increasing those numbers helps your use case? If that's the case, we can use an environment variable or alike to be able to configure those parameters.

**Comment by d0x2f** [comment]
I'll try and run a deployment with different values and get back to you with the results.

**Comment by d0x2f** [comment]
Hey @andresmgot 
After some investigation it seems that the root of the problem is actually the time taken by the `install` init container, it takes a while to run `npm install` with so many other pods trying to deploy at the same time.
Since the serverless-kubeless plugin is only looking for "Running" pods it can easily push past the timeouts while npm downloads and compiles packages.

I have a branch with these config options implemented let me know if you'd like this as a PR, but for us I think the real solution is to improve the install time. Happy to close this issue otherwise.

(https://github.com/d0x2f/serverless-kubeless/commit/9823fa8ce606114fcd40708a27afc95a2a89cfc2)

**Comment by andresmgot** [comment]
Thanks for the report and the link to the commit! Let's leave as it is then and check if someone else finds the same problem, we can re-evaluate then.
