### ISSUE TITLE
is invoke local working 

### ISSUE THREAD

**Issue by ericln** [serverless/serverless-kubeless#75]
i m trying out sls kubeless plugin, im using the `kubeless-nodejs` template to create a new function.
Executing the command `serverless invoke local --function capitalize --data 'this is a test' --raw` however, doesn't seem to return anything, am I missing something here?

**Comment by sebgoa** [comment]
I don't think it is supported, you need to target a kubernetes cluster that has kubeless installed.

cc/ @andresmgot

**Comment by andresmgot** [comment]
Yes. Right now the only way of using the plugin is to use a Kubernetes endpoint.

**Comment by ericln** [comment]
im not too familiar with the implementation of a plugins, can you shed some light on the effort of making it work with `invoke local` ? what needs to be implemented ?

**Comment by andresmgot** [comment]
It will be needed to mock a Kubernetes environment and redirect calls to use local runtimes binaries like`node` or `python`.

The main reason behind not having the `invoke local` command yet is that in the case of Kubeless you can easily deploy a Kubernetes environment locally using [Minikube](https://github.com/kubernetes/minikube) that will be more similar to the production environment than local runtimes.

If you are curious this is the implementation details for the command [`invoke local` for OpenWhisk](https://github.com/serverless/serverless-openwhisk/blob/master/invokeLocal/index.js#L93).

**Comment by Dorostkar** [comment]
Hi,
Please, someone, help me. I don't like to stuck with this error :(
{ NetworkingError: Invalid character in header content ["Authorization"]
    at validateHeader (_http_outgoing.js:506:11)
    at ClientRequest.setHeader (_http_outgoing.js:510:3)
    at new ClientRequest (_http_client.js:173:14)
    at Object.request (https.js:241:10)
    at Object.request (C:\Users\Sina\AppData\Roaming\npm\node_modules\serverless\node_modules\agent-base\patch-core.js:52:20)
    at features.constructor.handleRequest (E:\node\notes-app\node_modules\aws-sdk\lib\http\node.js:42:23)
    at executeSend (E:\node\notes-app\node_modules\aws-sdk\lib\event_listeners.js:304:29)
    at Request.SEND (E:\node\notes-app\node_modules\aws-sdk\lib\event_listeners.js:318:9)
    at Request.callListeners (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\node\notes-app\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\node\notes-app\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at callNextListener (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at E:\node\notes-app\node_modules\aws-sdk\lib\event_listeners.js:220:9
    at finish (E:\node\notes-app\node_modules\aws-sdk\lib\config.js:320:7)
    at E:\node\notes-app\node_modules\aws-sdk\lib\config.js:338:9
    at SharedIniFileCredentials.get (E:\node\notes-app\node_modules\aws-sdk\lib\credentials.js:126:7)
    at getAsyncCredentials (E:\node\notes-app\node_modules\aws-sdk\lib\config.js:332:24)
    at Config.getCredentials (E:\node\notes-app\node_modules\aws-sdk\lib\config.js:352:9)
    at Request.SIGN (E:\node\notes-app\node_modules\aws-sdk\lib\event_listeners.js:192:22)
    at Request.callListeners (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\node\notes-app\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\node\notes-app\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\node\notes-app\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Timeout.callNextListener [as _onTimeout] (E:\node\notes-app\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
  message: 'Invalid character in header content ["Authorization"]',
  code: 'NetworkingError',
  region: 'eu-west-1',
  hostname: 'dynamodb.eu-west-1.amazonaws.com',
  retryable: true,
  time: 2018-02-28T17:36:49.058Z }
{
    "statusCode": 500,
    "header": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Credentials": true
    },
    "body": "{\"status\":false}"
}
